experiments:
  - name: "baseline"
    train_mode: "baseline"
  
  - name: "scratch_lr1e-4"
    train_mode: "scratch"
    learning_rate: 1e-4
    epochs: 200
    batch_size: 64
    noise_type: "none"

  - name: "scratch_lr1e-3"
    train_mode: "scratch"
    learning_rate: 1e-3
    epochs: 200
    batch_size: 64
    noise_type: "none"

  - name: "scratch_lr1e-2"
    train_mode: "scratch"
    learning_rate: 1e-2
    epochs: 200
    batch_size: 64
    noise_type: "none"

  - name: "scratch_lr1e-4_bs32"
    train_mode: "scratch"
    learning_rate: 1e-4
    epochs: 200
    batch_size: 32
    noise_type: "none"

  - name: "scratch_lr1e-3_bs32"
    train_mode: "scratch"
    learning_rate: 1e-3
    epochs: 200
    batch_size: 32
    noise_type: "none"

  - name: "scratch_lr1e-2_bs32"
    train_mode: "scratch"
    learning_rate: 1e-2
    epochs: 200
    batch_size: 32
    noise_type: "none"

  - name: "scratch_lr1e-4_bs16"
    train_mode: "scratch"
    learning_rate: 1e-4
    epochs: 200
    batch_size: 16
    noise_type: "none"

  - name: "scratch_lr1e-3_bs16"
    train_mode: "scratch"
    learning_rate: 1e-3
    epochs: 200
    batch_size: 16
    noise_type: "none"

  - name: "scratch_lr1e-2_bs16"
    train_mode: "scratch"
    learning_rate: 1e-2
    epochs: 200
    batch_size: 16
    noise_type: "none"

